### ISSUE TITLE
Action to archive on release creation

### ISSUE THREAD

**Issue by TargetCrafter** [Vertco/KatanaForNinjaOne#26]
Create action to create archives for Chromium and Firefox when making a new release.

This should zip the contents of the BIN directory with the correct manifest file.
I'll name the manifest files manifest_firefox.json and manifest_chrome.json respectively for each archive.

**Comment by NathanVerkerk** [comment]
I have done some research.
It is best to make 2 folders: Firefox_manifest and Chromium_Manifest, in here we place the different manifest.json files, with the correct name (manifest.json).
With the action i will pick these manifests, and place them into the root of the extension src.
https://github.com/marketplace/actions/easy-zip-files

I will implement this as soon as the new file structure and extension is ready, #16.
