### ISSUE TITLE
Dark theme not working in specific page

### ISSUE THREAD

**Issue by Nathanymous** [Vertco/KatanaForNinjaOne#33]
While browsing trough NinjaOne i stumbled upon a page where dark mode is not working.
We should look into fixing it.
https://aad.rmmservice.eu/#/editor/cloudMonitor

**Comment by TargetCrafter** [comment]
This page seems to work just fine in my testing on multiple devices.
If you notice this issue again, please try checking the console for errors, maybe then we can look into it.
