### ISSUE TITLE
Description in store not pulled from _locales

### ISSUE THREAD

**Issue by Nathanymous** [Vertco/KatanaForNinjaOne#37]
When looking in the Microsoft add on store, i saw the description in NL and EN language did not match the description in the messages.json file in _locales.
We need to check this

**Comment by Nathanymous** [comment]
@TargetCrafter do you think you might have made a mistake when publishing the app to the app store?

**Comment by TargetCrafter** [comment]
There is a limit on the number of characters in the manifest extension, so the store has an extended description. This is also not filled automatically.

The description in the manifest is shown in the "manage extensions" tab of your browser:
![image](https://user-images.githubusercontent.com/47614276/224490376-6e927c09-993a-45ed-b2d0-f868d3b3ed01.png)

**Comment by Nathanymous** [comment]
Okay, clear. Thanks for the info
