### ISSUE TITLE
Add close button in theme menu

### ISSUE THREAD

**Issue by Nathanymous** [Vertco/KatanaForNinjaOne#42]
Add a close button to the theme menu, so it will be easier to understand how to close the menu when you didn't make changes

**Comment by TargetCrafter** [comment]
I disagree, the menu should close when clicking outside of the menu, just like the other menu's.

**Comment by Nathanymous** [comment]
I agree on that, but since you couldn't get that to work and we don't know if we can get this working we should have a close button. If we get it to work I prefer the click outside the menu
