### ISSUE TITLE
Theme not saved in Firefox

### ISSUE THREAD

**Issue by pretendor** [Vertco/KatanaForNinjaOne#56]
After updating to the latest plugin version the dark/light theme is not stored or saved.
after i close the browser and reopen it the default scheme (light) is enabled where katana say its selected as dark.

**Comment by Nathanymous** [comment]
I noticed the checkmark is on the right theme. So only the code for changing the theme itself isn't working.

**Comment by Nathanymous** [comment]
In a new tab the theme is also not included, it goes to the fallback theme (Light theme)

**Comment by TargetCrafter** [comment]
I did some testing on my own, but for me everything seems to work as expected.
The only thing with Firefox is that it seems that you need to allow the extension to modify the current page by clicking on the extension. This can be changed by right-clicking the extension and selecting " Always Allow on xxx.xx":
![image](https://github.com/Vertco/KatanaForNinjaOne/assets/47614276/06a6b5f3-1d47-47f9-ae6a-2aa3b4799f23)

**Comment by pretendor** [comment]
Fixed by myself.

**Comment by pretendor** [comment]
Problems is solved. seems like it was a one time occure
